[package]
name = "sqlfluffrs_dialects"
version.workspace = true
edition = "2021"

[dependencies]
hashbrown = "0.15.5"
once_cell = "1.21.3"
regex = { version = "1.11.2", features = ["perf"] }
fancy-regex = "0.16.2"
sqlfluffrs_types = { path = "../sqlfluffrs_types" }
