#
# This updates the current draft release notes when a PR is merged
#
name: Add to Release Notes
on:
  push:
    branches:
      - main
jobs:
  draft-release:
    runs-on: ubuntu-slim
    if: github.repository == 'sqlfluff/sqlfluff'
    steps:
    - name: Update release notes
      uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
