name: Deploy Docs

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Enable corepack
        run: |
          corepack enable

      - name: ğŸ’¾ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: docsv/pnpm-lock.yaml

      - name: ğŸ“„ Setup Pages
        uses: actions/configure-pages@v5
        if: ${{ !env.ACT }}

      - name: ï¿½ Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: ğŸ“¦ Install SQLFluff
        run: pip install -e .

      - name: ğŸ“¦ Install dependencies
        working-directory: docsv
        run: pnpm install --frozen-lockfile

      - name: âš’ï¸ Build with VitePress
        working-directory: docsv
        run: pnpm run docs:build

      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-pages-artifact@v4
        if: ${{ !env.ACT }}
        with:
          path: docsv/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    name: âœ… Deploy Docs
    steps:
      - name: âœ… Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v4
